ks = list(range(4, 20, 1))

rule all:
    input:
        expand('data/Human_nskewfcov_k{k}_params.npz',
               k=ks),
        expand('data/Human_{model}_k{k}_observables.npz',
            model=['train', 'test', 'ncov', 'nskew', 'nskewfcov'], k=ks)

rule train_test:
    output:
        'data/Human_train_k{k}_matrix.csv.gz',
        'data/Human_test_k{k}_matrix.csv.gz',
    script:
       'generate_reference_matrices.py' 

rule fit_ncov:
    input:
        'data/Human_train_k{k}_matrix.csv.gz'
    output:
        'data/Human_ncov_k{k}_matrix.csv.gz',
        'data/Human_ncov_k{k}_params.npz',
    script:
        'fit_ncov.py'

rule fit_nskew:
    input:
        'data/Human_train_k{k}_matrix.csv.gz',
        'data/Human_ncov_k{k}_params.npz'
    output:
        'data/Human_nskew_k{k}_matrix.csv.gz',
        'data/Human_nskew_k{k}_params.npz',
    script:
        'fit_nskew.py'

rule fit_nskewfcov:
    input:
        'data/Human_train_k{k}_matrix.csv.gz',
        'data/Human_nskew_k{k}_params.npz'
    output:
        'data/Human_nskewfcov_k{k}_matrix.csv.gz',
        'data/Human_nskewfcov_k{k}_params.npz',
    script:
        'fit_nskewfcov.py'

rule observables:
    input:
        'data/Human_{model}_k{k}_matrix.csv.gz'
    output:
        'data/Human_{model}_k{k}_observables.npz'
    script:
        'evaluate_observables.py'
