composition:
	seqtk comp ../../data/dna_chr21.fa.gz > data/composition_human_chr21.tsv
	seqtk comp ../../data/dna_human_all.fa.gz > data/composition_human.tsv
	seqtk comp ../../data/dna_pfalciparum.fasta > data/composition_pfalciparum.tsv
	seqtk comp ../../data/UP000008333PlasmodiumVivax.fasta.gz > data/composition_pvivax.tsv
	seqtk comp ../../data/UP000008553PlasmodiumYoeliiYoelii.fasta.gz > data/composition_pyoeliiyoelii.tsv
	seqtk comp ../../data/UP000031513PlasmodiumKnowlesi.fasta.gz > data/composition_pknowlesi.tsv
	seqtk comp ../../data/UP000074855PlasmodiumBerghei.fasta.gz > data/composition_pberghei.tsv


