
copycode:
	cp ../code . -r
	rm code/*/data/ -r
	rm code/*/.ipynb_checkpoints/ -r
	rm code/*/.gitignore
	rm code/.ipynb_checkpoints/ -r
	rm code/lib/ -r
	rm code/*.py -r
	rm code/*/__pycache__/ -r
	rm code/plots/ -r

posts:
	python code_to_posts.py

clean:
	rm -rf build *.c *.so *.pyc

